# Generated by Django 4.2.1 on 2023-06-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bloguploader',
            new_name='Blogpost',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
