# Generated by Django 4.2.1 on 2023-06-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainf', '0002_rename_bloguploader_blogpost_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default=None, null=True, upload_to='blog/')),
                ('content', models.TextField()),
            ],
        ),
    ]
