# Generated by Django 4.2.1 on 2023-06-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainf', '0003_blogcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='image/'),
        ),
    ]
